apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        image: mongo
        name: mongodb
        ports:
        - name: mongodbport
          containerPort: 27017
          protocol: TCP
